In [23]:
import numpy as np
import random 

In [12]:
arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [17]:
summ = np.sum(arr)
meann = np.mean(arr)
mediann = np.median(arr)
std = np.std(arr)
ind = np.where(arr > 10)
print("Sum -",summ)
print("Mean -",meann)
print("Median -",mediann)
print("Standard Deviation -",std)
print("Indices of Numbers greater than 10 -",ind[0])

Sum - 210
Mean - 10.5
Median - 10.5
Standard Deviation - 5.766281297335398
Indices of Numbers greater than 10 - [10 11 12 13 14 15 16 17 18 19]


In [21]:
arr1 = np.arange(1,17).reshape(4,4)
print("Array:\n", arr1)
transpose_arr = arr1.T
print("\nTranspose:\n", transpose_arr)
row_sum = np.sum(arr1, axis=1)
col_sum = np.sum(arr1, axis=0)
print("\nRow-wise sum:", row_sum)
print("Column-wise sum:", col_sum)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Row-wise sum: [10 26 42 58]
Column-wise sum: [28 32 36 40]


In [33]:
arr2 = np.random.randint(1,21,(3,3))
arr3 = np.random.randint(1,21,(3,3))
print("Two 3X3 matrices -\n",arr2,"\n\n",arr3)
print()

add = arr2 + arr3
sub = arr2 - arr3
multi = arr3 * arr3
dot = np.dot(arr2,arr3)
print("Addition =\n",add)
print()
print("Subtraction =\n",sub)
print()
print("Multiplication =\n",multi)
print()
print("Dot Product =\n",dot)

Two 3X3 matrices -
 [[14 16 18]
 [16 17 20]
 [ 2 18 15]] 

 [[13  6 13]
 [14 12  5]
 [ 2 15 10]]

Addition =
 [[27 22 31]
 [30 29 25]
 [ 4 33 25]]

Subtraction =
 [[ 1 10  5]
 [ 2  5 15]
 [ 0  3  5]]

Multiplication =
 [[169  36 169]
 [196 144  25]
 [  4 225 100]]

Dot Product =
 [[442 546 442]
 [486 600 493]
 [308 453 266]]


In [35]:
arr4 = np.arange(1, 13)
print("1D array :",arr4)
arr2D = arr4.reshape(3, 4)
print("\n3x4 Array:\n", arr2D)
sliced = arr2D[:2, -2:]
print("\nSliced Array (first 2 rows, last 2 columns):\n", sliced)

1D array : [ 1  2  3  4  5  6  7  8  9 10 11 12]

3x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sliced Array (first 2 rows, last 2 columns):
 [[3 4]
 [7 8]]
